sudo: false
language: node_js
node_js: "8.9.1"
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pip install awscli --upgrade --user
- travis_retry yarn install --frozen-lockfile
- travis_retry cd neo-codap && yarn install --frozen-lockfile && cd ..
before_script: npm run build
script: ./s3_deploy.sh
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - neo-codap/node_modules
